include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "flatpak@x86_64"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

variables:
    MANIFEST_PATH: "org.gnome.gitlab.wwarner.Solitaire.Devel.json"
    FLATPAK_MODULE: "solitaire"
    APP_ID: "org.gnome.gitlab.wwarner.Solitaire.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "org.gnome.gitlab.wwarner.Solitaire.Devel.flatpak"
    TARBALL_ARTIFACT_PATH: ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: [".flatpak@x86_64"]

nightly@x86_64:
  extends: ".publish_nightly"
  needs: ["flatpak@x86_64"]

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  image: "rust:slim"
  stage: ".pre"
  script:
    - rustup component add rustfmt
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
