include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

variables:
    FLATPAK_MODULE: "solitaire"
    MANIFEST_PATH: "org.gnome.gitlab.wwarner.Solitaire.Devel.json"
    APP_ID: "org.gnome.gitlab.wwarner.Solitaire.Devel"
    BUNDLE: "org.gnome.gitlab.wwarner.Solitaire.Devel.flatpak"

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: [".flatpak@x86_64"]

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  image: "rust:slim"
  stage: ".pre"
  script:
    - rustup component add rustfmt
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
